service: appsync-master-class-backend
frameworkVersion: '2'

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs12.x

custom:
  appSync:
    - ${file(serverless.appsync-api.yml)}

package:
  exclude:
    - package-lock.json
    - package.json

#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
